# Generates one add_test() per case reported by `axiom_roundtrip --list`.
#
# The test binary is the single source of truth for the list, so the platform
# conditionals inside its registry do not have to be mirrored here. Run at build
# time (not configure time) because it needs the built executable.
#
# Expects: TEST_EXECUTABLE, OUTPUT_FILE, WORKING_DIR.

execute_process(
    COMMAND "${TEST_EXECUTABLE}" --list
    OUTPUT_VARIABLE discovered
    ERROR_VARIABLE discovery_error
    RESULT_VARIABLE discovery_result
    OUTPUT_STRIP_TRAILING_WHITESPACE)

if(NOT discovery_result EQUAL 0)
    message(FATAL_ERROR
        "Could not list tests from ${TEST_EXECUTABLE} (exit ${discovery_result}): ${discovery_error}")
endif()

string(REPLACE "\n" ";" test_names "${discovered}")

set(content "# Generated by DiscoverRoundtripTests.cmake. Do not edit.\n")
foreach(name IN LISTS test_names)
    string(STRIP "${name}" name)
    if(name STREQUAL "")
        continue()
    endif()
    string(APPEND content
        "add_test([=[roundtrip.${name}]=] [=[${TEST_EXECUTABLE}]=] --test [=[${name}]=])\n"
        "set_tests_properties([=[roundtrip.${name}]=] PROPERTIES WORKING_DIRECTORY [=[${WORKING_DIR}]=])\n")
endforeach()

# Only rewrite when the set actually changed, so an unchanged list does not keep
# invalidating the build.
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" existing)
    if(existing STREQUAL content)
        return()
    endif()
endif()
file(WRITE "${OUTPUT_FILE}" "${content}")
